"""Genotyping-array raw data → VCF (RELEASE_PLAN 3.0.3).

Synthetic hg19 FASTA (chr1/chr2, 1000 bp) + hand-written 23andMe,
AncestryDNA and MyHeritage files whose rows exercise every rule of
array_to_vcf(); expectations come from the FASTA bases, not from the code.
"""

import gzip
import shutil
import sys
from pathlib import Path

import numpy as np
import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
PIPELINE = REPO_ROOT / "prs_research_pipeline"
sys.path.insert(0, str(PIPELINE))

from bluegen import array_input as ai  # noqa: E402
from bluegen import genome_build as gb  # noqa: E402

HAS_BCFTOOLS = shutil.which("bcftools") is not None


@pytest.fixture
def fasta(tmp_path):
    rng = np.random.RandomState(5)
    seqs = {"chr1": "".join(rng.choice(list("ACGT"), 1000)), "chr2": "".join(rng.choice(list("ACGT"), 1000)),
            "chrX": "".join(rng.choice(list("ACGT"), 1000)), "chrM": "".join(rng.choice(list("ACGT"), 1000))}
    fa = tmp_path / "hg19.fa"
    fai = []
    with open(fa, "wb") as fh:
        for name, seq in seqs.items():
            fh.write(f">{name}\n".encode())
            offset = fh.tell()
            for i in range(0, len(seq), 50):
                fh.write((seq[i:i + 50] + "\n").encode())
            fai.append(f"{name}\t{len(seq)}\t{offset}\t50\t51")
    (tmp_path / "hg19.fa.fai").write_text("\n".join(fai) + "\n")
    return fa, seqs


def other(b):
    return {"A": "C", "C": "G", "G": "T", "T": "A"}[b]


def _records(path):
    out = []
    with gzip.open(path, "rt") as fh:
        for line in fh:
            if not line.startswith("#"):
                out.append(line.rstrip("\n").split("\t"))
    return out


def test_sniff_format_and_build_hint(tmp_path):
    f = tmp_path / "a.txt"
    f.write_text("# This data file generated by 23andMe at: 2024\n# ...reference human assembly build 37...\n"
                 "# rsid\tchromosome\tposition\tgenotype\nrs1\t1\t100\tAA\n")
    assert ai.sniff_format(f) == ("23andme", "GRCh37")
    g = tmp_path / "b.txt"
    g.write_text("#AncestryDNA raw data download\n#...human reference build 38...\n"
                 "rsid\tchromosome\tposition\tallele1\tallele2\nrs1\t1\t100\tA\tA\n")
    assert ai.sniff_format(g) == ("ancestrydna", "GRCh38")
    h = tmp_path / "c.csv"
    h.write_text("##MyHeritage DNA raw data.\nRSID,CHROMOSOME,POSITION,RESULT\n\"rs1\",\"1\",\"100\",\"AA\"\n")
    assert ai.sniff_format(h) == ("myheritage", None)


def test_iter_genotypes_handles_the_three_layouts(tmp_path):
    f = tmp_path / "a.txt"
    f.write_text("# rsid\tchromosome\tposition\tgenotype\nrs1\t1\t100\tAG\nrs2\tX\t50\tA\nrs3\tMT\t7\t--\n"
                 "rs4\t2\t9\tII\ni700\t2\t10\tCC\n")
    rows = list(ai.iter_genotypes(f, "23andme"))
    assert rows == [("rs1", "1", 100, "A", "G"), ("rs2", "X", 50, "A", "A"), ("rs3", "MT", 7, "-", "-"),
                    ("rs4", "2", 9, "I", "I"), ("i700", "2", 10, "C", "C")]
    g = tmp_path / "b.txt"
    g.write_text("rsid\tchromosome\tposition\tallele1\tallele2\nrs1\t23\t100\tA\tG\nrs2\t26\t7\t0\t0\nrs3\t25\t5\tC\tC\n")
    assert list(ai.iter_genotypes(g, "ancestrydna")) == [("rs1", "X", 100, "A", "G"), ("rs2", "MT", 7, "-", "-"),
                                                          ("rs3", "X", 5, "C", "C")]
    h = tmp_path / "c.csv"
    h.write_text('RSID,CHROMOSOME,POSITION,RESULT\n"rs1","1","100","AG"\n"rs2","2","5","--"\n')
    assert list(ai.iter_genotypes(h, "myheritage")) == [("rs1", "1", 100, "A", "G"), ("rs2", "2", 5, "-", "-")]


@pytest.mark.skipif(not HAS_BCFTOOLS, reason="needs bcftools")
def test_array_to_vcf_applies_every_rule(tmp_path, fasta):
    fa, seqs = fasta
    r = lambda c, p: seqs[c][p - 1]  # noqa: E731
    rows = [
        ("rs_homref", "1", 100, r("chr1", 100) * 2),                        # 0/0 written
        ("rs_het", "1", 200, r("chr1", 200) + other(r("chr1", 200))),        # 0/1
        ("rs_homalt", "1", 300, other(r("chr1", 300)) * 2),                  # 1/1
        ("rs_multi", "1", 400, other(r("chr1", 400)) + other(other(r("chr1", 400)))),  # 1/2
        ("rs_nocall", "1", 500, "--"),
        ("rs_indel", "1", 600, "DI"),
        ("rs_x_hap", "X", 100, other(r("chrX", 100))),                       # haploid → 1/1
        ("rs_mt", "MT", 100, r("chrM", 100) * 2),                            # 0/0 on MT
        ("rs_dup", "1", 100, r("chr1", 100) * 2),                            # duplicate site
        ("rs_badchr", "7_random", 10, "AA"),
    ]
    f = tmp_path / "me.txt"
    f.write_text("# 23andMe build 37\n# rsid\tchromosome\tposition\tgenotype\n"
                 + "".join(f"{a}\t{b}\t{c}\t{d}\n" for a, b, c, d in rows))
    out = tmp_path / "me.vcf.gz"
    st = ai.array_to_vcf(f, out, fa, sample_id="ME")
    assert st["n_rows"] == 10 and st["n_written"] == 6
    assert (st["n_hom_ref"], st["n_het"], st["n_hom_alt"], st["n_multiallelic"]) == (2, 1, 2, 1)
    assert st["n_nocall"] == 1 and st["n_indel_code"] == 1 and st["n_duplicate_site"] == 1
    assert st["n_unknown_chrom"] == 1
    recs = {x[2]: x for x in _records(out)}
    assert recs["rs_homref"][3:5] == [r("chr1", 100), "."] and recs["rs_homref"][9] == "0/0"
    assert recs["rs_het"][9] == "0/1" and recs["rs_homalt"][9] == "1/1"
    assert recs["rs_multi"][4].count(",") == 1 and recs["rs_multi"][9] == "1/2"
    assert recs["rs_x_hap"][0] == "X" and recs["rs_x_hap"][9] == "1/1"
    assert recs["rs_mt"][0] == "MT"
    assert (tmp_path / "me.vcf.gz.tbi").exists()
    assert gb.detect_build(out)[0] == "GRCh37"          # header carries GRCh37 contig lengths
    assert st["format"] == "23andme"


@pytest.mark.skipif(not HAS_BCFTOOLS, reason="needs bcftools")
def test_grch38_array_rows_are_lifted_before_ref_lookup(tmp_path, fasta):
    """hg38 chr1 [100,200) → hg19 chr1 [300,400) on +; hg38 chr2 [100,110) → hg19
    chr2 reverse [500,510). Same synthetic chain as test_genome_build."""
    from pyliftover import LiftOver
    fa, seqs = fasta
    chain = tmp_path / "hg38ToHg19.chain"
    chain.write_text("chain 1000 chr1 1000 + 100 200 chr1 1000 + 300 400 1\n100\n\n"
                     "chain 900 chr2 1000 + 100 110 chr2 1000 - 500 510 2\n10\n\n")
    comp = {"A": "T", "C": "G", "G": "C", "T": "A"}
    b351 = seqs["chr1"][350]
    b500 = seqs["chr2"][499]
    rows = [("rs_plus", "1", 151, b351 + other(b351)),           # → chr1:351 het
            ("rs_minus", "2", 101, comp[b500] + comp[b500]),      # → chr2:500 hom-ref after complement
            ("rs_unmapped", "1", 50, "AA")]
    f = tmp_path / "me38.txt"
    f.write_text("# 23andMe build 38\n" + "".join(f"{a}\t{b}\t{c}\t{d}\n" for a, b, c, d in rows))
    out = tmp_path / "me38.vcf.gz"
    st = ai.array_to_vcf(f, out, fa, sample_id="ME", lifter=LiftOver(str(chain)))
    assert st["n_written"] == 2 and st["n_unmapped"] == 1 and st["n_strand_flipped"] == 1
    recs = {x[2]: x for x in _records(out)}
    assert recs["rs_plus"][1] == "351" and recs["rs_plus"][9] == "0/1"
    assert recs["rs_minus"][1] == "500" and recs["rs_minus"][3] == b500 and recs["rs_minus"][9] == "0/0"


def test_detect_array_build_from_markers(tmp_path):
    panel = {f"rs{k}": ("1", 301 + 5 * k) for k in range(12)}          # GRCh37 positions (inside [300,400) 0-based)
    f37 = tmp_path / "a37.txt"
    f37.write_text("# no build in header\n" + "".join(f"rs{k}\t1\t{301 + 5 * k}\tAA\n" for k in range(12)))
    build, ev = ai.detect_array_build(f37, panel, chain_19to38=None)
    assert build == "GRCh37" and ev["method"] == "marker_positions" and ev["panel_markers_found"] == 12
    chain = tmp_path / "hg19ToHg38.chain"
    chain.write_text("chain 1000 chr1 1000 + 300 400 chr1 1000 + 100 200 1\n100\n\n")   # hg38 = hg19 − 200
    f38 = tmp_path / "a38.txt"
    f38.write_text("# no build in header\n" + "".join(f"rs{k}\t1\t{101 + 5 * k}\tAA\n" for k in range(12)))
    build, ev = ai.detect_array_build(f38, panel, chain_19to38=chain)
    assert build == "GRCh38" and ev["match_grch38"] == 12 and ev["match_grch37"] == 0
    # header hint only when markers are too few
    f = tmp_path / "hint.txt"
    f.write_text("# 23andMe ... build 37 ...\nrs999\t1\t5\tAA\n")
    assert ai.detect_array_build(f, panel, None)[0] == "GRCh37"
    g = tmp_path / "nohint.txt"
    g.write_text("# nothing\nrs999\t1\t5\tAA\n")
    assert ai.detect_array_build(g, panel, None)[0] == "unknown"
